"""DATA-3, the next 30%: expedites with costs, multi-tier risk, the weekly pack,
and genuine calibration against a simulated future.

    python extend.py
    python extend.py --report-only

Four gaps the first build named:
  1. no expedite recommendations with cost estimates -- the analysis identified
     shortages and stopped short of what to do about them
  2. single-tier supplier view -- a sub-tier supplier feeding three of your
     "independent" sources is the concentration risk nobody sees
  3. no weekly materials-review pack generated by code
  4. no GENUINE calibration -- the first build's calibration section checked the
     percentiles against the same simulations they came from, which verifies
     arithmetic and not the model
"""
from __future__ import annotations

import json
import pathlib
import sys
import time

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "src"))

import buildability as B  # noqa: E402
import supplier_analytics as SA  # noqa: E402
import supply  # noqa: E402

OUT = ROOT / "out"


# ---------------------------------------------------------------------------
# 1. expedites
# ---------------------------------------------------------------------------

def expedite_options(base, drivers, mc) -> list[dict]:
    """For each gating part, what an expedite buys and what it costs.

    The number that decides an expedite is not the premium -- it is the premium
    against the MARGIN OF THE UNITS IT UNBLOCKS. A $4,000 air freight on a part
    that unblocks 12 units at $900 margin is obviously worth it; the same premium
    on a part that unblocks 12 units at $120 margin is not, and the reason
    materials meetings go badly is that the premium is visible on an invoice and
    the margin is not visible at all.
    """
    rows = []
    for d in drivers[:8]:
        part = d["part"]
        c = base.components.get(part)
        if c is None:
            continue
        s = base.suppliers[c.supplier_id]
        # Expedite compresses lead time; premium scales with how much you compress.
        for mode, compression, premium_mult in (("air freight", 0.45, 4.0),
                                                ("partial shipment", 0.70, 1.8),
                                                ("supplier overtime", 0.85, 1.25)):
            days_saved = s.lead_mean_days * (1 - compression)
            # Units unblocked: how many of the shortfall this part gates.
            gating_units = d["times_gating_in_sim"] / max(1, mc["n_sims"])
            premium = c.unit_cost * (premium_mult - 1.0) * max(50.0, gating_units * 10)
            rows.append({
                "part": part, "supplier": c.supplier_id, "mode": mode,
                "lead_mean_days": s.lead_mean_days,
                "days_saved": days_saved,
                "premium_usd": premium,
                "unit_cost": c.unit_cost,
                "single_sourced": c.single_sourced,
                "order_by_day": d["order_by_day"],
                "recovers_runway": bool(d["order_by_day"] + days_saved > 0),
            })
    return rows


# ---------------------------------------------------------------------------
# 2. multi-tier
# ---------------------------------------------------------------------------

def build_subtier(base, seed: int = 31) -> dict:
    """Assign each tier-1 supplier a tier-2 source, and find the concentrations.

    THE POINT: dual-sourcing a part is worthless if both sources buy from the same
    sub-tier. This is the failure that took out automotive semiconductors and
    aerospace castings repeatedly -- the risk register said "dual sourced" and the
    dependency graph said otherwise, because nobody had the second tier.
    """
    rng = np.random.default_rng(seed)
    tier2 = [f"T2-{i+1:02d}" for i in range(12)]
    # Deliberately skewed: a few sub-tier suppliers serve many tier-1s.
    weights = np.array([6.0, 5.0, 4.0] + [1.0] * (len(tier2) - 3))
    weights = weights / weights.sum()
    mapping = {sid: str(rng.choice(tier2, p=weights)) for sid in base.suppliers}

    # For each PART, which tier-2 sources does it ultimately depend on?
    part_t2: dict[str, set] = {}
    for part, c in base.components.items():
        if c.level == 2 and c.supplier_id:
            part_t2.setdefault(part, set()).add(mapping[c.supplier_id])

    # Concentration: how many parts, and how many products, sit behind each T2.
    req = supply.unit_requirements(base)
    t2_parts: dict[str, list] = {}
    for part, s in part_t2.items():
        for t in s:
            t2_parts.setdefault(t, []).append(part)

    rows = []
    for t, parts in sorted(t2_parts.items(), key=lambda kv: -len(kv[1])):
        products = {p for p in base.products if any(pt in req[p] for pt in parts)}
        rows.append({
            "tier2": t, "tier1_suppliers": sum(1 for v in mapping.values() if v == t),
            "parts_behind_it": len(parts),
            "products_affected": sorted(products),
            "n_products_affected": len(products),
        })
    return {"mapping": mapping, "concentration": rows,
            "n_tier2": len(t2_parts)}


def hidden_single_source(base, subtier) -> list[dict]:
    """Parts that look multi-sourced at tier 1 but converge at tier 2.

    Here every part has ONE tier-1 supplier, so the honest version of this check
    is at the SUPPLIER level: which tier-1 suppliers a buyer would treat as
    independent alternatives, but which share a sub-tier.
    """
    mapping = subtier["mapping"]
    by_t2: dict[str, list] = {}
    for sid, t2 in mapping.items():
        by_t2.setdefault(t2, []).append(sid)
    out = []
    for t2, sids in sorted(by_t2.items(), key=lambda kv: -len(kv[1])):
        if len(sids) < 2:
            continue
        parts = [p for p, c in base.components.items()
                 if c.level == 2 and c.supplier_id in sids]
        out.append({"tier2": t2, "tier1_count": len(sids),
                    "tier1_suppliers": sorted(sids)[:6],
                    "parts_exposed": len(parts)})
    return out


# ---------------------------------------------------------------------------
# 3. genuine calibration
# ---------------------------------------------------------------------------

def calibrate_against_future(base, n_futures: int = 60, n_sims: int = 120,
                             seed: int = 777) -> dict:
    """The calibration the first build could not do.

    RESULTS.md checked what fraction of simulations fell below their own P50 --
    which is a self-consistency check on the arithmetic, not on the model, and it
    said so. This is the real thing: draw N independent FUTURES from the same
    generative process, treat each as "what actually happened", and ask how often
    the forecast fan contained it.

    A P10-P90 band should contain the outcome 80% of the time. If it contains it
    99% of the time the fan is too wide and nobody will trust the P10; if 50%,
    the plan is being presented as more certain than it is.
    """
    rng = np.random.default_rng(seed)
    mc = B.monte_carlo(base, n_sims=n_sims, seed=seed)
    fan = mc["fan"]

    inside = {p: 0 for p in base.products}
    below_p10 = {p: 0 for p in base.products}
    above_p90 = {p: 0 for p in base.products}
    total = {p: 0 for p in base.products}

    for i in range(n_futures):
        actual = B.buildable(base, rng=np.random.default_rng(int(rng.integers(1e9))),
                             stochastic=True)
        for p in base.products:
            a = np.asarray(actual["built"][p], dtype=float)
            lo = np.asarray(fan[p]["p10"], dtype=float)
            hi = np.asarray(fan[p]["p90"], dtype=float)
            inside[p] += int(((a >= lo) & (a <= hi)).sum())
            below_p10[p] += int((a < lo).sum())
            above_p90[p] += int((a > hi).sum())
            total[p] += len(a)

    rows = []
    for p in base.products:
        t = max(1, total[p])
        rows.append({
            "product": p,
            "pct_inside_p10_p90": 100.0 * inside[p] / t,
            "pct_below_p10": 100.0 * below_p10[p] / t,
            "pct_above_p90": 100.0 * above_p90[p] / t,
            "target_inside_pct": 80.0,
        })
    return {"n_futures": n_futures, "n_sims_in_fan": n_sims, "per_product": rows,
            "mean_inside_pct": float(np.mean([r["pct_inside_p10_p90"] for r in rows]))}


# ---------------------------------------------------------------------------

def main() -> None:
    OUT.mkdir(exist_ok=True)
    if "--report-only" in sys.argv:
        prev = json.loads((OUT / "extensions.json").read_text())
        (ROOT / "docs" / "EXTENSIONS.md").write_text(report(prev), encoding="utf-8")
        print("re-rendered docs/EXTENSIONS.md")
        return

    t0 = time.perf_counter()
    quick = "--quick" in sys.argv
    base = supply.build()
    res: dict = {}

    print("1/4 Monte Carlo + expedite options ...", flush=True)
    mc = B.monte_carlo(base, n_sims=60 if quick else 200)
    drivers = B.shortage_drivers(base, mc)
    res["expedites"] = expedite_options(base, drivers, mc)
    res["drivers"] = drivers[:8]
    print(f"    {len(res['expedites'])} expedite options across "
          f"{len(res['drivers'])} gating parts", flush=True)

    print("2/4 multi-tier supplier risk ...", flush=True)
    st = build_subtier(base)
    res["subtier"] = {"n_tier2": st["n_tier2"],
                      "concentration": st["concentration"][:8]}
    res["hidden_single_source"] = hidden_single_source(base, st)[:6]
    top = st["concentration"][0]
    print(f"    top sub-tier {top['tier2']} sits behind {top['parts_behind_it']} "
          f"parts and {top['n_products_affected']} products", flush=True)

    print("3/4 genuine calibration against simulated futures ...", flush=True)
    res["calibration"] = calibrate_against_future(
        base, n_futures=25 if quick else 60, n_sims=60 if quick else 150)
    print(f"    P10-P90 contains the outcome "
          f"{res['calibration']['mean_inside_pct']:.1f}% of the time "
          f"(target 80%)", flush=True)

    print("4/4 the weekly materials pack ...", flush=True)
    res["pack"] = weekly_pack(base, mc, drivers, res)
    (OUT / "materials_review_pack.md").write_text(res["pack"], encoding="utf-8")
    res["wall_seconds"] = time.perf_counter() - t0

    (OUT / "extensions.json").write_text(json.dumps(res, indent=2, default=str))
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "EXTENSIONS.md").write_text(report(res), encoding="utf-8")
    print(f"\nwrote docs/EXTENSIONS.md and out/materials_review_pack.md "
          f"({res['wall_seconds']:.0f}s)")


def weekly_pack(base, mc, drivers, res) -> str:
    """The artifact the Monday meeting actually runs on, generated by code."""
    L = ["# Weekly Materials Review", "",
         "*Generated by `extend.py`. Every number traces to "
         "`out/extensions.json`.*", "",
         "## 1. Can we build the plan?", ""]
    L.append("| product | 13-week demand | P50 buildable | P10 | fill at P50 |")
    L.append("|---|---|---|---|---|")
    for p in base.products:
        f = mc["fan"][p]
        dem = float(np.sum(f["demand"]))
        p50 = float(np.sum(f["p50"]))
        p10 = float(np.sum(f["p10"]))
        L.append(f"| {p} | {dem:,.0f} | {p50:,.0f} | {p10:,.0f} | "
                 f"{100*p50/max(dem,1):.0f}% |")

    L += ["", "## 2. Top shortage drivers — action required", ""]
    L.append("| part | supplier | single source | first impact | order by | status |")
    L.append("|---|---|---|---|---|---|")
    for d in drivers[:6]:
        status = "**PAST DUE**" if d["already_too_late"] else "on track"
        L.append(f"| {d['part']} | {d['supplier']} | "
                 f"{'YES' if d['single_sourced'] else 'no'} | "
                 f"{('week ' + str(d['first_impact_week'])) if d['first_impact_week'] else '—'} | "
                 f"day {d['order_by_day']:+.0f} | {status} |")

    L += ["", "## 3. Recommended expedites", ""]
    L.append("| part | mode | days saved | premium | recovers runway? |")
    L.append("|---|---|---|---|---|")
    for e in res["expedites"][:8]:
        L.append(f"| {e['part']} | {e['mode']} | {e['days_saved']:.0f} | "
                 f"${e['premium_usd']:,.0f} | "
                 f"{'yes' if e['recovers_runway'] else 'no'} |")

    L += ["", "## 4. Sub-tier concentration", ""]
    L.append("| tier-2 source | tier-1 suppliers behind it | parts | products |")
    L.append("|---|---|---|---|")
    for c in res["subtier"]["concentration"][:5]:
        L.append(f"| {c['tier2']} | {c['tier1_suppliers']} | "
                 f"{c['parts_behind_it']} | {c['n_products_affected']} |")
    L += ["", "*Prepared for the Monday materials review. Items marked PAST DUE "
          "need a decision in this meeting, not next week.*", ""]
    return "\n".join(L)


def report(res: dict) -> str:
    L: list[str] = []
    A = L.append
    A("# DATA-3 extensions — generated by `extend.py`, not hand-edited\n")

    A("## 1. Expedites — what to DO about a shortage\n")
    A("The first build identified shortage drivers and stopped there. An expedite "
      "recommendation is what a materials manager is actually asking for, and the "
      "number that decides it is **not the premium** — it is the premium against "
      "the margin of the units it unblocks. That comparison is hard in practice "
      "for a structural reason: the premium arrives on an invoice and the margin "
      "is not visible from the materials system at all.\n")
    A("| part | supplier | mode | lead mean | days saved | premium | recovers runway? |")
    A("|---|---|---|---|---|---|---|")
    for e in res["expedites"][:12]:
        A(f"| {e['part']} | {e['supplier']} | {e['mode']} | "
          f"{e['lead_mean_days']:.0f} d | {e['days_saved']:.0f} d | "
          f"${e['premium_usd']:,.0f} | "
          f"{'**yes**' if e['recovers_runway'] else 'no'} |")
    rec = [e for e in res["expedites"] if e["recovers_runway"]]
    A(f"\n**{len(rec)} of {len(res['expedites'])} options actually recover the "
      "runway** — i.e. the days saved exceed the days already lost past the "
      "order-by date. The rest are money spent on a part that will still be late, "
      "which is the expedite decision people get wrong most often: air freight on "
      "a part that needed ordering six weeks ago buys a faster arrival of "
      "something that is still after the line stops.")

    A("\n## 2. Multi-tier risk — the concentration nobody sees\n")
    A("**Dual-sourcing a part is worthless if both sources buy from the same "
      "sub-tier.** This is the failure that took out automotive semiconductors and "
      "aerospace castings repeatedly: the risk register said \"dual sourced\" and "
      "the dependency graph said otherwise, because nobody had the second tier.\n")
    A("| tier-2 source | tier-1 suppliers behind it | parts exposed | products affected |")
    A("|---|---|---|---|")
    for c in res["subtier"]["concentration"]:
        A(f"| {c['tier2']} | {c['tier1_suppliers']} | {c['parts_behind_it']} | "
          f"{c['n_products_affected']} ({', '.join(c['products_affected'])}) |")
    top = res["subtier"]["concentration"][0]
    A(f"\n**{top['tier2']} sits behind {top['tier1_suppliers']} tier-1 suppliers, "
      f"{top['parts_behind_it']} parts, and {top['n_products_affected']} of the "
      "product line.** A single-tier risk score cannot see that number, because at "
      "tier 1 those parts are spread across many independent-looking vendors.\n")
    if res.get("hidden_single_source"):
        A("Tier-1 suppliers a buyer would treat as alternatives, that in fact "
          "converge:\n")
        A("| tier-2 | tier-1 suppliers sharing it | parts exposed |")
        A("|---|---|---|")
        for h in res["hidden_single_source"]:
            A(f"| {h['tier2']} | {h['tier1_count']} ({', '.join(h['tier1_suppliers'])}) | "
              f"{h['parts_exposed']} |")
    A("\n**Honest scope:** the tier-2 mapping is *generated*, not discovered. In "
      "reality it is the hardest data in this whole project to obtain — suppliers "
      "treat their own sources as confidential, and the mapping is assembled from "
      "questionnaires, customs records and industry knowledge, then goes stale. "
      "The analysis here shows what the data buys once you have it; getting it is "
      "the actual work and it is not a modelling problem.")

    c = res["calibration"]
    A("\n## 3. Calibration — the real version\n")
    A("RESULTS.md §2 checked what fraction of simulations fell below their own "
      "P50, and said outright that this verifies arithmetic rather than the model. "
      "This is the honest test: draw "
      f"**{c['n_futures']} independent futures** from the generative process, "
      "treat each as what actually happened, and ask how often the forecast fan "
      f"(built from {c['n_sims_in_fan']} simulations) contained it.\n")
    A("| product | % inside P10–P90 | % below P10 | % above P90 | target |")
    A("|---|---|---|---|---|")
    for r in c["per_product"]:
        A(f"| {r['product']} | **{r['pct_inside_p10_p90']:.1f}%** | "
          f"{r['pct_below_p10']:.1f}% | {r['pct_above_p90']:.1f}% | 80% |")
    m = c["mean_inside_pct"]
    A(f"\n**Mean coverage: {m:.1f}% against a target of 80%.**\n")
    if m > 90:
        A("The band is **too wide**. An interval that contains the outcome far more "
          "often than advertised is not conservative-and-therefore-safe: it is a "
          "forecast nobody will plan against, because the P10 stops being a "
          "meaningful floor. The likely cause is that the fan and the futures are "
          "drawn from the same lead-time distributions, so the only variation the "
          "fan sees is the variation it was built from — a real fan also has to "
          "carry parameter uncertainty, which would widen the *true* outcome spread "
          "rather than the predicted one.")
    elif m < 70:
        A("The band is **too narrow** — the plan is being presented as more certain "
          "than it is, which is the more dangerous direction. A materials manager "
          "who commits to a P10 that is breached a third of the time will stop "
          "believing the fan after the second occasion.")
    else:
        A("Coverage is close to nominal, which is what makes the P10 usable as a "
          "commitment floor rather than a decoration.")
    A("\nThis is still a calibration against *my own generator*, and that limit is "
      "irreducible without real receipt history: the futures and the fan share a "
      "data-generating process, so what is verified is internal consistency of the "
      "propagation, not that supplier lead times behave this way.")

    A("\n## 4. The weekly materials pack\n")
    A("Generated to `out/materials_review_pack.md` — the artifact the Monday "
      "meeting runs on, produced by code rather than assembled by hand at 7 a.m. "
      "Four sections: can we build the plan, top shortage drivers with order-by "
      "dates, recommended expedites with costs, and sub-tier concentration.\n")
    A("The design rule for this document is that **every row implies an action or "
      "it does not belong**. A materials pack that reports status without naming "
      "the decision is the thing that makes the meeting an hour long and the "
      "decisions late.")

    A("\n---\n*Regenerate with `python extend.py`.*")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    main()
