"""DATA-3 end-to-end: BOM -> buildability -> shortage drivers -> order-by dates.

    python run_supply.py
    python run_supply.py --quick
    python run_supply.py --report-only
"""
from __future__ import annotations

import json
import pathlib
import sys
import time

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "src"))

import buildability as B  # noqa: E402
import supplier_analytics as SA  # noqa: E402
import supply  # noqa: E402

OUT = ROOT / "out"


def main() -> None:
    quick = "--quick" in sys.argv
    OUT.mkdir(exist_ok=True)
    if "--report-only" in sys.argv:
        prev = json.loads((OUT / "results.json").read_text())
        (ROOT / "docs").mkdir(exist_ok=True)
        (ROOT / "docs" / "RESULTS.md").write_text(report(prev), encoding="utf-8")
        print("re-rendered docs/RESULTS.md")
        return

    t0 = time.perf_counter()
    print("1/5 building the supply base ...", flush=True)
    base = supply.build()
    n_parts = sum(1 for c in base.components.values() if c.level == 2)
    n_subs = sum(1 for c in base.components.values() if c.level == 1)
    res: dict = {"base": {
        "products": base.products, "purchased_parts": n_parts,
        "sub_assemblies": n_subs, "bom_lines": len(base.bom),
        "suppliers": len(base.suppliers),
        "single_sourced_parts": sum(1 for c in base.components.values() if c.single_sourced),
        "open_pos": sum(1 for p in base.pos if p.received_day is None),
        "received_pos": sum(1 for p in base.pos if p.received_day is not None),
        "horizon_weeks": supply.WEEKS,
        "planted_disruptions": base.planted_disruptions,
    }}
    print(f"    {len(base.products)} products, {n_subs} sub-assemblies, {n_parts} "
          f"purchased parts, {len(base.bom)} BOM lines, {len(base.suppliers)} suppliers",
          flush=True)

    print("2/5 supplier analytics ...", flush=True)
    flags = SA.detect_deterioration(base)
    res["deterioration"] = {"flags": [f for f in flags if f["flagged"]],
                            "score": SA.score_detection(base, flags)}
    res["otif_gap"] = SA.otif_gap(base)[:10]
    res["risk"] = {"weights": SA.RISK_WEIGHTS, "top": SA.risk_score(base)[:10]}
    sc = res["deterioration"]["score"]
    print(f"    deterioration: precision {sc['precision']:.2f}, recall {sc['recall']:.2f} "
          f"({len(sc['true_positives'])}/{len(sc['planted'])} planted caught)", flush=True)

    print("3/5 deterministic buildability + shortage attribution ...", flush=True)
    det = B.buildable(base)
    res["deterministic"] = {
        "built": {p: v.tolist() for p, v in det["built"].items()},
        "demand": {p: base.demand[p].tolist() for p in base.products},
        "gating_events": len(det["gating"]),
    }

    print("4/5 Monte Carlo buildability ...", flush=True)
    mc = B.monte_carlo(base, n_sims=80 if quick else 300)
    res["monte_carlo"] = {k: v for k, v in mc.items() if not k.startswith("_")}

    print("5/5 shortage drivers with order-by dates ...", flush=True)
    res["drivers"] = B.shortage_drivers(base, mc)
    res["allocation"] = B.compare_allocation_policies(base, n_sims=40 if quick else 120)

    # Calibration: is P50 actually the median of what happens?
    sims = mc["_sims"]
    cal = {}
    for p in base.products:
        s = sims[p]
        p50 = np.percentile(s, 50, axis=0)
        p10 = np.percentile(s, 10, axis=0)
        p90 = np.percentile(s, 90, axis=0)
        cal[p] = {
            "pct_below_p50": float(100 * np.mean(s < p50[None, :])),
            "pct_inside_p10_p90": float(100 * np.mean((s >= p10[None, :]) & (s <= p90[None, :]))),
        }
    res["calibration"] = cal
    res["wall_seconds"] = time.perf_counter() - t0

    (OUT / "results.json").write_text(json.dumps(res, indent=2, default=str))
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "RESULTS.md").write_text(report(res), encoding="utf-8")
    print(f"\nwrote docs/RESULTS.md and out/results.json ({res['wall_seconds']:.0f}s)")


def report(res: dict) -> str:
    L: list[str] = []
    A = L.append
    b = res["base"]
    A("# DATA-3 results — generated by `run_supply.py`, not hand-edited\n")
    A(f"{len(b['products'])} end products, {b['sub_assemblies']} sub-assemblies, "
      f"**{b['purchased_parts']} purchased parts**, {b['bom_lines']} BOM lines, "
      f"{b['suppliers']} suppliers ({b['single_sourced_parts']} single-sourced parts), "
      f"{b['open_pos']} open POs and {b['received_pos']} received POs of history. "
      f"Horizon: **{b['horizon_weeks']} weeks**.\n")
    A("Why 13 weeks: it covers most purchased-part lead times plus a planning "
      "cycle, so an order placed today still lands inside the window. Beyond it, "
      "forecast uncertainty starts to dominate supply uncertainty and the analysis "
      "is answering a sales question wearing a materials hat.")

    A("\n## 1. Buildability — the only question that matters\n")
    A("Deterministic pass (promise dates taken at face value), units per week:\n")
    A("| product | " + " | ".join(f"w{i+1}" for i in range(b["horizon_weeks"])) + " |")
    A("|---" * (b["horizon_weeks"] + 1) + "|")
    for p in b["products"]:
        built = res["deterministic"]["built"][p]
        dem = res["deterministic"]["demand"][p]
        A(f"| {p} demand | " + " | ".join(f"{d:.0f}" for d in dem) + " |")
        A(f"| {p} buildable | " + " | ".join(
            f"**{x:.0f}**" if x < d else f"{x:.0f}" for x, d in zip(built, dem)) + " |")
    A(f"\n{res['deterministic']['gating_events']} (product, week) pairs are short "
      "under the deterministic plan. Bold = short.")

    A("\n## 2. The same plan as a distribution\n")
    mc = res["monte_carlo"]
    A(f"{mc['n_sims']} Monte Carlo runs over supplier lead-time distributions and "
      "quality rejection. P10 / P50 / P90 buildable units per week:\n")
    for p in b["products"]:
        f = mc["fan"][p]
        A(f"\n**{p}**\n")
        A("| week | demand | P10 | P50 | P90 |")
        A("|---|---|---|---|---|")
        for i in range(b["horizon_weeks"]):
            A(f"| {i+1} | {f['demand'][i]:.0f} | {f['p10'][i]:.0f} | "
              f"{f['p50'][i]:.0f} | {f['p90'][i]:.0f} |")
    A("\nThis is the artifact that changes the materials meeting. \"P50 says 120\" "
      "invites a commitment; \"P10 84, P50 120, P90 140, and the gating part is "
      "PRT-0041 from a single source\" invites a decision. A point estimate on a "
      "supply plan is a forecast pretending to be a fact.")

    cal = res["calibration"]
    A("\n### Is the fan calibrated?\n")
    A("| product | % of simulations below the P50 | % inside P10–P90 |")
    A("|---|---|---|")
    for p, c in cal.items():
        A(f"| {p} | {c['pct_below_p50']:.1f}% | {c['pct_inside_p10_p90']:.1f}% |")
    A("\nThese should be near 50% and 80%. They are *self-consistency* checks — the "
      "percentiles are computed from the same simulations they are scored against, "
      "so this verifies the arithmetic, not the model. Deviations come from "
      "discreteness (buildable units are integers, so many simulations tie exactly "
      "at the percentile). **Genuine calibration would require comparing the fan "
      "against realised outcomes, which needs a simulated future this project does "
      "not run** — that is named in the README as not built.")

    A("\n## 3. Shortage drivers, with order-by dates\n")
    A("| part | supplier | single source | times gating | first impact | lead mean | lead P95 | **order by (day)** | too late? |")
    A("|---|---|---|---|---|---|---|---|---|")
    for d in res["drivers"]:
        A(f"| {d['part']} | {d['supplier']} | {'**yes**' if d['single_sourced'] else 'no'} | "
          f"{d['times_gating_in_sim']} | "
          f"{('week ' + str(d['first_impact_week'])) if d['first_impact_week'] else '—'} | "
          f"{d['lead_mean_days']:.0f} d | {d['lead_p95_days']:.0f} d | "
          f"**day {d['order_by_day']:+.0f}** | "
          f"{'**ALREADY LATE**' if d['already_too_late'] else 'no'} |")
    late = sum(1 for d in res["drivers"] if d["already_too_late"])
    A(f"\n{late} of {len(res['drivers'])} top drivers are **already past their "
      "order-by date** — the runway was consumed before anyone looked.\n")
    A("The order-by date is computed from the **P95** lead time, not the mean. "
      "Ordering a gating part to its mean lead time means arriving late half the "
      "time, which for the part that stops the line is not a plan. That single "
      "substitution is the difference between an alert that is a fact (\"you will "
      "be short in week 7\") and an alert that is a decision (\"order by day −3 or "
      "the line stops in week 7\").")

    A("\n## 4. Supplier deterioration — caught by distributions, not averages\n")
    sc = res["deterioration"]["score"]
    A(f"Planted disruptions: {len(sc['planted'])}. Flagged: {len(sc['flagged'])}. "
      f"**Precision {sc['precision']:.2f}, recall {sc['recall']:.2f}.**\n")
    A("| disruption type | planted | caught | caught by the P95 trigger alone |")
    A("|---|---|---|---|")
    for kind, k in sc["by_kind"].items():
        A(f"| {kind} | {k['planted']} | {k['caught']} | {k['by_p95_only']} |")
    A("\nThe `tail_blowout` row is the argument for watching distributions. Those "
      "suppliers have a mean lead time that has barely moved and a P95 that has "
      "doubled — they are the ones that will stop a line, and every mean-based "
      "monitor and every OTD percentage says they are fine. The P95 and variance "
      "triggers are what catch them.\n")
    dbl = sc["by_kind"].get("lead_time_doubling", {})
    if dbl and dbl.get("caught", 0) < dbl.get("planted", 1):
        A(f"**The `lead_time_doubling` row is a poor result and is not dressed up: "
          f"{dbl['caught']} of {dbl['planted']} caught.** These should be the EASY "
          "ones — the mean itself moves. They are missed because the detector "
          "compares a 120-day recent window against a 245-day baseline on ~15 "
          "receipts per supplier, and with that few points a doubled mean does not "
          "always clear a 1.25x ratio threshold against a noisy baseline. The fix "
          "is not a cleverer statistic, it is more history per supplier-part or a "
          "sequential test (CUSUM on lead time) that accumulates evidence instead "
          "of comparing two windows — DATA-2 in this portfolio has the machinery "
          "and the two are not wired together.\n")
    A(f"At precision {sc['precision']:.2f} this raises roughly one false alarm per "
      "true one. In a weekly materials review that may be acceptable — a flagged "
      "supplier costs a phone call — but it is a real operating point and it is "
      "reported rather than tuned until it looked good. A threshold sweep to "
      "characterise the tradeoff properly is not built.\n")
    A("| supplier | mean ratio | P95 ratio | sd ratio | triggers |")
    A("|---|---|---|---|---|")
    for f in res["deterioration"]["flags"][:12]:
        A(f"| {f['supplier_id']} | {f['mean_ratio']:.2f}× | {f['p95_ratio']:.2f}× | "
          f"{f['sd_ratio']:.2f}× | {', '.join(f['triggers'])} |")

    A("\n## 5. OTIF, and the definitional trap\n")
    A("On-time-in-full against **which** promise: the original one made when the "
      "order was placed, or the latest agreed reschedule?\n")
    A("| supplier | receipts | OTIF vs original | OTIF vs latest promise | gap (pts) |")
    A("|---|---|---|---|---|")
    for r in res["otif_gap"][:10]:
        A(f"| {r['supplier_id']} | {r['n_receipts']} | {r['otif_vs_original_pct']:.1f}% | "
          f"{r['otif_vs_latest_promise_pct']:.1f}% | **{r['gaming_gap_pts']:+.1f}** |")
    A("\nAgainst the latest reschedule, a supplier who is chronically late but "
      "always calls ahead scores near 100%. That is the number suppliers prefer and "
      "it is the ERP default in a lot of configurations, because the promise field "
      "gets overwritten in place. **The scorecard here uses the ORIGINAL promise**, "
      "and reports the gap as its own metric — a direct measure of how much a "
      "supplier is managing their score rather than their delivery.")

    A("\n## 6. Composite risk, with the weights visible\n")
    w = res["risk"]["weights"]
    A("Weights: " + ", ".join(f"`{k}` {v:.2f}" for k, v in w.items()) + ".\n")
    A("| supplier | risk | single-sourced parts | lead CV | reject rate | financial | largest contributor |")
    A("|---|---|---|---|---|---|---|")
    for r in res["risk"]["top"]:
        top = max(r["contributions"], key=r["contributions"].get)
        A(f"| {r['supplier_id']} | {r['risk_score']:.3f} | {r['single_sourced_parts']} | "
          f"{r['lead_cv']:.2f} | {r['quality_reject_rate']*100:.2f}% | "
          f"{r['financial_score']:.2f} | {top} |")
    A("\nThe weights are printed and the score decomposes into contributions, "
      "because the first question a sourcing manager asks is \"why is this supplier "
      "red\" — and a composite with hidden weights is an opinion wearing a number's "
      "clothes.")

    A("\n## 7. Allocation policy when a shared component is short\n")
    A("| policy | total P50 units | worst product fill rate | " +
      " | ".join(b["products"]) + " |")
    A("|---|---|---|" + "---|" * len(b["products"]))
    for a in res["allocation"]:
        cells = " | ".join(f"{a['per_product'][p]['fill_rate_pct']:.1f}%"
                           for p in b["products"])
        A(f"| {a['policy']} | {a['total_p50']:.0f} | "
          f"{a['worst_product_fill_pct']:.1f}% | {cells} |")
    A("\nShared components are where the shortage maths gets interesting, because "
      "someone has to decide who gets the part. That is a business policy, not an "
      "arithmetic fact, and the three policies produce different plans and "
      "different angry people. The job of the analysis is to make the tradeoff "
      "explicit and quantified — not to pick.")

    A("\n---\n*Every supplier, BOM line, lead-time distribution and disruption is "
      "generated by `src/supply.py`, which is what makes the detection precision "
      "and recall in §4 scoreable.*")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    main()
